create table tb_bet (id int8 generated by default as identity, luck_numbers bytea, user_id int8, primary key (id));
create table tb_user (id int8 generated by default as identity, email varchar(255), primary key (id));
alter table if exists tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table if exists tb_bet add constraint FKdslgbu024wy7198w9rr6ou4vh foreign key (user_id) references tb_user;
